// AUTOGENERATED by reduce-tools migration. Edit by adding/removing entries here,
// not by re-introducing per-file tool modules.

export interface ProviderEndpoint {
  url: string;
  maxChars?: number;
}

export interface ProviderEntry {
  brand: string;
  defaultEndpoint: string;
  endpoints: Record<string, ProviderEndpoint>;
}

export const PROVIDERS: Record<string, ProviderEntry> = {
  "akamai": {
    brand: "akamai",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://www.akamaistatus.com/api/v2/components.json" },
      "incidents": { url: "https://www.akamaistatus.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://www.akamaistatus.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://www.akamaistatus.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://www.akamaistatus.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://www.akamaistatus.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://www.akamaistatus.com/api/v2/status.json" },
      "summary": { url: "https://www.akamaistatus.com/api/v2/summary.json" },
    },
  },
  "anthropic": {
    brand: "anthropic",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.anthropic.com/api/v2/components.json" },
      "incidents": { url: "https://status.anthropic.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.anthropic.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.anthropic.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.anthropic.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.anthropic.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.anthropic.com/api/v2/status.json" },
      "summary": { url: "https://status.anthropic.com/api/v2/summary.json" },
    },
  },
  "anydesk": {
    brand: "anydesk",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.anydesk.com/api/v2/components.json" },
      "incidents": { url: "https://status.anydesk.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.anydesk.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.anydesk.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.anydesk.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.anydesk.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.anydesk.com/api/v2/status.json" },
      "summary": { url: "https://status.anydesk.com/api/v2/summary.json" },
    },
  },
  "apple": {
    brand: "apple",
    defaultEndpoint: "system_status",
    endpoints: {
      "system_status": { url: "https://www.apple.com/de/support/systemstatus/" },
    },
  },
  "atlassian": {
    brand: "atlassian",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.atlassian.com/api/v2/components.json" },
      "incidents": { url: "https://status.atlassian.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.atlassian.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.atlassian.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.atlassian.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.atlassian.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.atlassian.com/api/v2/status.json" },
      "summary": { url: "https://status.atlassian.com/api/v2/summary.json" },
    },
  },
  "auth0": {
    brand: "auth0",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.auth0.com/", maxChars: 20000 },
    },
  },
  "aws": {
    brand: "aws",
    defaultEndpoint: "health_status",
    endpoints: {
      "health_status": { url: "https://health.aws.amazon.com/health/status" },
    },
  },
  "azure": {
    brand: "azure",
    defaultEndpoint: "status",
    endpoints: {
      "status": { url: "https://azure.status.microsoft/en-us/status/feed/" },
    },
  },
  "bitdefender": {
    brand: "bitdefender",
    defaultEndpoint: "status",
    endpoints: {
      "components": { url: "https://ssems.gravityzone.bitdefender.com/api/v1/components" },
      "notices": { url: "https://ssems.gravityzone.bitdefender.com/api/v1/notices", maxChars: 25000 },
      "status": { url: "https://ssems.gravityzone.bitdefender.com/api/v1/status" },
    },
  },
  "brevo": {
    brand: "brevo",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.brevo.com/api/v2/components.json" },
      "incidents": { url: "https://status.brevo.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.brevo.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.brevo.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.brevo.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.brevo.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.brevo.com/api/v2/status.json" },
      "summary": { url: "https://status.brevo.com/api/v2/summary.json" },
    },
  },
  "cloudflare": {
    brand: "cloudflare",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://www.cloudflarestatus.com/api/v2/components.json" },
      "incidents": { url: "https://www.cloudflarestatus.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://www.cloudflarestatus.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://www.cloudflarestatus.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://www.cloudflarestatus.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://www.cloudflarestatus.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://www.cloudflarestatus.com/api/v2/status.json" },
      "summary": { url: "https://www.cloudflarestatus.com/api/v2/summary.json" },
    },
  },
  "cloudinary": {
    brand: "cloudinary",
    defaultEndpoint: "status",
    endpoints: {
      "status": { url: "https://status.cloudinary.com/api/v2/status.json" },
    },
  },
  "cohere": {
    brand: "cohere",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.cohere.com/api/v2/components.json" },
      "incidents": { url: "https://status.cohere.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.cohere.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.cohere.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.cohere.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.cohere.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.cohere.com/api/v2/status.json" },
      "summary": { url: "https://status.cohere.com/api/v2/summary.json" },
    },
  },
  "crowdstrike": {
    brand: "crowdstrike",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.crowdstrike.com/", maxChars: 12000 },
    },
  },
  "databricks": {
    brand: "databricks",
    defaultEndpoint: "status",
    endpoints: {
      "status": { url: "https://status.databricks.com/1.0/status/5cf02dde58a00904bda41926" },
    },
  },
  "datadog": {
    brand: "datadog",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.datadoghq.com/api/v2/components.json" },
      "incidents": { url: "https://status.datadoghq.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.datadoghq.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.datadoghq.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.datadoghq.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.datadoghq.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.datadoghq.com/api/v2/status.json" },
      "summary": { url: "https://status.datadoghq.com/api/v2/summary.json" },
    },
  },
  "datev": {
    brand: "datev",
    defaultEndpoint: "incidents",
    endpoints: {
      "incidents": { url: "https://api.datev-status.de/v1/incidents" },
    },
  },
  "deepseek": {
    brand: "deepseek",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.deepseek.com/", maxChars: 20000 },
    },
  },
  "digitalocean": {
    brand: "digitalocean",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.digitalocean.com/api/v2/components.json" },
      "incidents": { url: "https://status.digitalocean.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.digitalocean.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.digitalocean.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.digitalocean.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.digitalocean.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.digitalocean.com/api/v2/status.json" },
      "summary": { url: "https://status.digitalocean.com/api/v2/summary.json" },
    },
  },
  "discord": {
    brand: "discord",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://discordstatus.com/api/v2/components.json" },
      "incidents": { url: "https://discordstatus.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://discordstatus.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://discordstatus.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://discordstatus.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://discordstatus.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://discordstatus.com/api/v2/status.json" },
      "summary": { url: "https://discordstatus.com/api/v2/summary.json" },
    },
  },
  "dropbox": {
    brand: "dropbox",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.dropbox.com/api/v2/components.json" },
      "incidents": { url: "https://status.dropbox.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.dropbox.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.dropbox.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.dropbox.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.dropbox.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.dropbox.com/api/v2/status.json" },
      "summary": { url: "https://status.dropbox.com/api/v2/summary.json" },
    },
  },
  "duo": {
    brand: "duo",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.duo.com/api/v2/components.json" },
      "incidents": { url: "https://status.duo.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.duo.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.duo.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.duo.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.duo.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.duo.com/api/v2/status.json" },
      "summary": { url: "https://status.duo.com/api/v2/summary.json" },
    },
  },
  "fastly": {
    brand: "fastly",
    defaultEndpoint: "rss",
    endpoints: {
      "rss": { url: "https://www.fastlystatus.com/rss/", maxChars: 25000 },
    },
  },
  "fireworks": {
    brand: "fireworks",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.fireworks.ai/", maxChars: 20000 },
    },
  },
  "flyio": {
    brand: "flyio",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.flyio.net/", maxChars: 20000 },
    },
  },
  "github": {
    brand: "github",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://www.githubstatus.com/api/v2/components.json" },
      "incidents": { url: "https://www.githubstatus.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://www.githubstatus.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://www.githubstatus.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://www.githubstatus.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://www.githubstatus.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://www.githubstatus.com/api/v2/status.json" },
      "summary": { url: "https://www.githubstatus.com/api/v2/summary.json" },
    },
  },
  "gitlab": {
    brand: "gitlab",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.gitlab.com/", maxChars: 20000 },
    },
  },
  "google_workspace": {
    brand: "google_workspace",
    defaultEndpoint: "products",
    endpoints: {
      "incidents": { url: "https://www.google.com/appsstatus/dashboard/incidents.json" },
      "products": { url: "https://www.google.com/appsstatus/dashboard/products.json" },
    },
  },
  "groq": {
    brand: "groq",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://groqstatus.com/", maxChars: 20000 },
    },
  },
  "hetzner": {
    brand: "hetzner",
    defaultEndpoint: "status",
    endpoints: {
      "status": { url: "https://status.hetzner.com/" },
    },
  },
  "hubspot": {
    brand: "hubspot",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.hubspot.com/api/v2/components.json" },
      "incidents": { url: "https://status.hubspot.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.hubspot.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.hubspot.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.hubspot.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.hubspot.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.hubspot.com/api/v2/status.json" },
      "summary": { url: "https://status.hubspot.com/api/v2/summary.json" },
    },
  },
  "ionos": {
    brand: "ionos",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://www.ionos-status.com/api/v2/components.json" },
      "incidents": { url: "https://www.ionos-status.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://www.ionos-status.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://www.ionos-status.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://www.ionos-status.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://www.ionos-status.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://www.ionos-status.com/api/v2/status.json" },
      "summary": { url: "https://www.ionos-status.com/api/v2/summary.json" },
    },
  },
  "keeper": {
    brand: "keeper",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://statuspage.keeper.io/api/v2/components.json" },
      "incidents": { url: "https://statuspage.keeper.io/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://statuspage.keeper.io/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://statuspage.keeper.io/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://statuspage.keeper.io/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://statuspage.keeper.io/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://statuspage.keeper.io/api/v2/status.json" },
      "summary": { url: "https://statuspage.keeper.io/api/v2/summary.json" },
    },
  },
  "lexware": {
    brand: "lexware",
    defaultEndpoint: "status",
    endpoints: {
      "status": { url: "https://status.lexware.de/api/v1/status" },
    },
  },
  "linear": {
    brand: "linear",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://linearstatus.com/api/v2/components.json" },
      "incidents": { url: "https://linearstatus.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://linearstatus.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://linearstatus.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://linearstatus.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://linearstatus.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://linearstatus.com/api/v2/status.json" },
      "summary": { url: "https://linearstatus.com/api/v2/summary.json" },
    },
  },
  "mailchimp": {
    brand: "mailchimp",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.mailchimp.com/", maxChars: 20000 },
    },
  },
  "mailgun": {
    brand: "mailgun",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.mailgun.com/api/v2/components.json" },
      "incidents": { url: "https://status.mailgun.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.mailgun.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.mailgun.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.mailgun.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.mailgun.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.mailgun.com/api/v2/status.json" },
      "summary": { url: "https://status.mailgun.com/api/v2/summary.json" },
    },
  },
  "microsoft365": {
    brand: "microsoft365",
    defaultEndpoint: "status",
    endpoints: {
      "status": { url: "https://status.cloud.microsoft/" },
    },
  },
  "mistral": {
    brand: "mistral",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.mistral.ai/", maxChars: 20000 },
    },
  },
  "mollie": {
    brand: "mollie",
    defaultEndpoint: "summary",
    endpoints: {
      "summary": { url: "https://status.mollie.com/summary.json" },
    },
  },
  "mongodb": {
    brand: "mongodb",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.mongodb.com/api/v2/components.json" },
      "incidents": { url: "https://status.mongodb.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.mongodb.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.mongodb.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.mongodb.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.mongodb.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.mongodb.com/api/v2/status.json" },
      "summary": { url: "https://status.mongodb.com/api/v2/summary.json" },
    },
  },
  "moonshot": {
    brand: "moonshot",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.moonshot.cn/", maxChars: 20000 },
    },
  },
  "neon": {
    brand: "neon",
    defaultEndpoint: "summary",
    endpoints: {
      "summary": { url: "https://neonstatus.com/api/v1/summary" },
    },
  },
  "netlify": {
    brand: "netlify",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://www.netlifystatus.com/api/v2/components.json" },
      "incidents": { url: "https://www.netlifystatus.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://www.netlifystatus.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://www.netlifystatus.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://www.netlifystatus.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://www.netlifystatus.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://www.netlifystatus.com/api/v2/status.json" },
      "summary": { url: "https://www.netlifystatus.com/api/v2/summary.json" },
    },
  },
  "newrelic": {
    brand: "newrelic",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.newrelic.com/api/v2/components.json" },
      "incidents": { url: "https://status.newrelic.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.newrelic.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.newrelic.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.newrelic.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.newrelic.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.newrelic.com/api/v2/status.json" },
      "summary": { url: "https://status.newrelic.com/api/v2/summary.json" },
    },
  },
  "ninjaone": {
    brand: "ninjaone",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.ninjaone.com/api/v2/components.json" },
      "incidents": { url: "https://status.ninjaone.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.ninjaone.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.ninjaone.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.ninjaone.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.ninjaone.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.ninjaone.com/api/v2/status.json" },
      "summary": { url: "https://status.ninjaone.com/api/v2/summary.json" },
    },
  },
  "notion": {
    brand: "notion",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.notion.so/", maxChars: 20000 },
    },
  },
  "npm": {
    brand: "npm",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.npmjs.org/api/v2/components.json" },
      "incidents": { url: "https://status.npmjs.org/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.npmjs.org/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.npmjs.org/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.npmjs.org/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.npmjs.org/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.npmjs.org/api/v2/status.json" },
      "summary": { url: "https://status.npmjs.org/api/v2/summary.json" },
    },
  },
  "okta": {
    brand: "okta",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.okta.com/", maxChars: 20000 },
    },
  },
  "onepassword": {
    brand: "onepassword",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.1password.com/api/v2/components.json" },
      "incidents": { url: "https://status.1password.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.1password.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.1password.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.1password.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.1password.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.1password.com/api/v2/status.json" },
      "summary": { url: "https://status.1password.com/api/v2/summary.json" },
    },
  },
  "openai": {
    brand: "openai",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.openai.com/api/v2/components.json" },
      "incidents": { url: "https://status.openai.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.openai.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.openai.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.openai.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.openai.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.openai.com/api/v2/status.json" },
      "summary": { url: "https://status.openai.com/api/v2/summary.json" },
    },
  },
  "openrouter": {
    brand: "openrouter",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.openrouter.ai/", maxChars: 20000 },
    },
  },
  "pagerduty": {
    brand: "pagerduty",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.pagerduty.com/", maxChars: 20000 },
    },
  },
  "paypal": {
    brand: "paypal",
    defaultEndpoint: "rss",
    endpoints: {
      "atom": { url: "https://www.paypal-status.com/feed/atom" },
      "rss": { url: "https://www.paypal-status.com/feed/rss" },
    },
  },
  "peoplefone": {
    brand: "peoplefone",
    defaultEndpoint: "global",
    endpoints: {
      "global": { url: undefined },
    },
  },
  "perplexity": {
    brand: "perplexity",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.perplexity.com/", maxChars: 20000 },
    },
  },
  "planetscale": {
    brand: "planetscale",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://www.planetscalestatus.com/", maxChars: 20000 },
    },
  },
  "postmark": {
    brand: "postmark",
    defaultEndpoint: "status",
    endpoints: {
      "status": { url: "https://status.postmarkapp.com/api/v1/status" },
    },
  },
  "railway": {
    brand: "railway",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.railway.com/default", maxChars: 20000 },
    },
  },
  "render": {
    brand: "render",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.render.com/api/v2/components.json" },
      "incidents": { url: "https://status.render.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.render.com/api/v2/incidents/unresolved.json" },
      "status": { url: "https://status.render.com/api/v2/status.json" },
      "summary": { url: "https://status.render.com/api/v2/summary.json" },
    },
  },
  "salesforce": {
    brand: "salesforce",
    defaultEndpoint: "status_page",
    endpoints: {
      "instances": { url: "https://api.status.salesforce.com/v1/instances", maxChars: 30000 },
      "status_page": { url: "https://status.salesforce.com/", maxChars: 12000 },
    },
  },
  "scaleway": {
    brand: "scaleway",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.scaleway.com/api/v2/components.json" },
      "incidents": { url: "https://status.scaleway.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.scaleway.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.scaleway.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.scaleway.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.scaleway.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.scaleway.com/api/v2/status.json" },
      "summary": { url: "https://status.scaleway.com/api/v2/summary.json" },
    },
  },
  "sendgrid": {
    brand: "sendgrid",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.sendgrid.com/api/v2/components.json" },
      "incidents": { url: "https://status.sendgrid.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.sendgrid.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.sendgrid.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.sendgrid.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.sendgrid.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.sendgrid.com/api/v2/status.json" },
      "summary": { url: "https://status.sendgrid.com/api/v2/summary.json" },
    },
  },
  "sentry": {
    brand: "sentry",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.sentry.io/api/v2/components.json" },
      "incidents": { url: "https://status.sentry.io/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.sentry.io/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.sentry.io/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.sentry.io/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.sentry.io/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.sentry.io/api/v2/status.json" },
      "summary": { url: "https://status.sentry.io/api/v2/summary.json" },
    },
  },
  "shopify": {
    brand: "shopify",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.shopify.com/", maxChars: 20000 },
    },
  },
  "slack": {
    brand: "slack",
    defaultEndpoint: "current",
    endpoints: {
      "current": { url: "https://slack-status.com/api/v2.0.0/current" },
      "history": { url: "https://slack-status.com/api/v2.0.0/history" },
    },
  },
  "snowflake": {
    brand: "snowflake",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.snowflake.com/api/v2/components.json" },
      "incidents": { url: "https://status.snowflake.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.snowflake.com/api/v2/incidents/unresolved.json" },
      "status": { url: "https://status.snowflake.com/api/v2/status.json" },
      "summary": { url: "https://status.snowflake.com/api/v2/summary.json" },
    },
  },
  "sophos": {
    brand: "sophos",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.sophos.com/", maxChars: 12000 },
    },
  },
  "stripe": {
    brand: "stripe",
    defaultEndpoint: "current",
    endpoints: {
      "current": { url: "https://status.stripe.com/current" },
      "current_atom": { url: "https://status.stripe.com/current/atom.xml", maxChars: 25000 },
      "current_full": { url: "https://status.stripe.com/current/full", maxChars: 25000 },
    },
  },
  "supabase": {
    brand: "supabase",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.supabase.com/api/v2/components.json" },
      "incidents": { url: "https://status.supabase.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.supabase.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.supabase.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.supabase.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.supabase.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.supabase.com/api/v2/status.json" },
      "summary": { url: "https://status.supabase.com/api/v2/summary.json" },
    },
  },
  "teamviewer": {
    brand: "teamviewer",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.teamviewer.com/api/v2/components.json" },
      "incidents": { url: "https://status.teamviewer.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.teamviewer.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.teamviewer.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.teamviewer.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.teamviewer.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.teamviewer.com/api/v2/status.json" },
      "summary": { url: "https://status.teamviewer.com/api/v2/summary.json" },
    },
  },
  "together": {
    brand: "together",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.together.ai/", maxChars: 20000 },
    },
  },
  "twilio": {
    brand: "twilio",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.twilio.com/api/v2/components.json" },
      "incidents": { url: "https://status.twilio.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.twilio.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.twilio.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.twilio.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.twilio.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.twilio.com/api/v2/status.json" },
      "summary": { url: "https://status.twilio.com/api/v2/summary.json" },
    },
  },
  "vercel": {
    brand: "vercel",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://www.vercel-status.com/api/v2/components.json" },
      "incidents": { url: "https://www.vercel-status.com/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://www.vercel-status.com/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://www.vercel-status.com/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://www.vercel-status.com/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://www.vercel-status.com/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://www.vercel-status.com/api/v2/status.json" },
      "summary": { url: "https://www.vercel-status.com/api/v2/summary.json" },
    },
  },
  "vultr": {
    brand: "vultr",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.vultr.com/", maxChars: 20000 },
    },
  },
  "xai": {
    brand: "xai",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.x.ai/", maxChars: 20000 },
    },
  },
  "zendesk": {
    brand: "zendesk",
    defaultEndpoint: "status_page",
    endpoints: {
      "status_page": { url: "https://status.zendesk.com/", maxChars: 20000 },
    },
  },
  "zoom": {
    brand: "zoom",
    defaultEndpoint: "summary",
    endpoints: {
      "components": { url: "https://status.zoom.us/api/v2/components.json" },
      "incidents": { url: "https://status.zoom.us/api/v2/incidents.json" },
      "incidents_unresolved": { url: "https://status.zoom.us/api/v2/incidents/unresolved.json" },
      "scheduled_maintenances": { url: "https://status.zoom.us/api/v2/scheduled-maintenances.json" },
      "scheduled_maintenances_active": { url: "https://status.zoom.us/api/v2/scheduled-maintenances/active.json" },
      "scheduled_maintenances_upcoming": { url: "https://status.zoom.us/api/v2/scheduled-maintenances/upcoming.json" },
      "status": { url: "https://status.zoom.us/api/v2/status.json" },
      "summary": { url: "https://status.zoom.us/api/v2/summary.json" },
    },
  },
};

export const PROVIDER_KEYS = Object.keys(PROVIDERS).sort();

export const ALL_ENDPOINT_KEYS = Array.from(
  new Set(Object.values(PROVIDERS).flatMap((p) => Object.keys(p.endpoints))),
).sort();
